airebeam_customer_portal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users.views.Error404View import Error404View
handler404 = Error404View.as_view()

urlpatterns = [
    url(r'^change_password/', include('change_password.urls')),
    url(r'^reset_password/', include('reset_password.urls')),
    url(r'^terms/', include('terms_and_conditions.urls')),
    url(r'^operator/', include('agents.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^forgot_password/', include('forgot_password.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^radiostats/', include('radiostats.urls')),
    url(r'^mbr_online_check/', include('mbr_online_check.urls')),
    url(r'^tickets/', include('tickets.urls')),
    url(r'^', include('dashboard.urls')),

] 

tickets/urls.py
from django.conf.urls import url

from tickets import views_function
from tickets.views.CustomerTicketsView import CustomerTicketsView
from tickets.views.CustomerAllTicketsView import CustomerAllTicketsView
from tickets.views.TicketDetailView import TicketDetailView
from tickets.views.CategoriesView import CategoriesView
from tickets.views.SubCategoriesView import SubCategoriesView
from tickets.views.TicketConversationView import TicketConversationView
from tickets.views.ServicesView import ServicesView
from tickets.views.ServiceDetailView import ServiceDetailView
from tickets.views.TicketUpdateView import TicketUpdateView
from tickets.views.TicketReplyView import TicketReplyView
from tickets.views.TicketCreateForm import TicketCreateFormView 
from tickets.views.GenerateUpdatePaymentTicket import GenerateUpdatePaymentTicket
from tickets.views.ThanksUpdatePaymentView import ThanksUpdatePaymentView

app_name = 'tickets'
urlpatterns = [
	url(r'^categories$', CategoriesView.as_view(), name = 'categories'),
	url(r'^get_form/(?P<sub_cat_id>[0-9]+)$', TicketCreateFormView.as_view(), name = 'get_form'),
	url(r'^index$', CustomerAllTicketsView.as_view(), name = 'index'),
	url(r'^view_ticket/(?P<ticket_id>[0-9]+)$', TicketDetailView.as_view(), name = 'view_ticket'),
	url(r'^create_reply/(?P<ticket_id>[0-9]+)$', TicketReplyView.as_view(), name = 'create_reply'),
	url(r'^customer_recent_tickets$', CustomerTicketsView.as_view(), name = 'customer_recent_tickets$'),
	url(r'^sub_categories/(?P<sub_cat_id>[0-9]+)$', SubCategoriesView.as_view(), name = 'sub_categories'),
	url(r'^get_ticket_conversation/(?P<ticket_id>[0-9]+)$', TicketConversationView.as_view(), name = 'get_ticket_conversation'),
	url(r'^service_description/(?P<service_id>[0-9]+)$', ServiceDetailView.as_view(), name = 'service_description'),
	url(r'^updated_wh', views_function.updated_wh, name = 'updated_webhook'),
	url(r'^update_ticket/(?P<ticket_id>[0-9]+)$', TicketUpdateView.as_view(), name = 'update_ticket'),
	url(r'^services/(?P<group_id>[0-9]+)$', ServicesView.as_view(), name = 'services'),
	url(r'^generate_up_ticket$', GenerateUpdatePaymentTicket.as_view(), name = 'generate_up_ticket'),
	url(r'^thanks_update_payment$', ThanksUpdatePaymentView.as_view(), name = 'thanks_update_payment'),
	
]

users/urls.py
from django.conf.urls import url

from users import views_function
from users.views.LoginFormView import LoginFormView
from users.views.LogoutView import LogoutView

app_name = 'users'
urlpatterns = [
	url(r'^loggedin$', views_function.loggedin, name = 'loggedin'),
	url(r'^login$', LoginFormView.as_view(), name='login'),
	url(r'^logout$', LogoutView.as_view(), name = 'logout'),
	url(r'^extend_base_view$', views_function.extend_base_view, name = 'extend_base_view'),
	url(r'^get_pdf$', views_function.get_pdf, name = 'get_pdf'),	
]

tickets/views/CategoriesView.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.utils import checksession, getfromSession
from airebeam_customer_portal.utils import check_if_session_time_exceeds
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from tickets.models import Categories
from airebeam_customer_portal.enum import PasswordForceReset
from airebeam_customer_portal import utils

class CategoriesView(UserView):
    '''
    Fetches and return parent categories from db on get support form.
    '''
    template_name = 'tickets/categories.html'
    def get(self, request):
        if checksession(AppMsgs.MBRKEY, request):
            login_time = getfromSession(AppMsgs.LOGIN_TIME_KEY, request)
            is_session_exceded = check_if_session_time_exceeds(login_time)
            force_reset = utils.safe_cast(self.get_force_reset_pass(), int)
    #         Logout and redirect to login page
            if is_session_exceded:
                return HttpResponseRedirect(reverse('users:logout'))

#           Redirect to dashboard if force reset password is set.  
            if force_reset == PasswordForceReset.FORCE_RESET or self.get_terms_url() is not None:
                return redirect('dashboard:index')
            
            parent_categories = Categories.get_parent_categories()
            sub_categories = Categories.get_sub_categories(3)
            
            context = {AppMsgs.PARENT_CATEGORIES_KEY:parent_categories, AppMsgs.SUBCATEGORIES_KEY:sub_categories}

            success_str = request.GET.get('s', '')
            if success_str != '':
                context['success'] = int(success_str)

            return render(request, self.template_name, context)
        else:
            return HttpResponseRedirect(reverse('users:logout'))

tickets/views/CustomerAllTicketsView.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.AppServices.TicketService import TicketService
from airebeam_customer_portal.utils import checksession, getfromSession
from airebeam_customer_portal.utils import check_if_session_time_exceeds
from airebeam_customer_portal.enum import AppStatus
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView

class CustomerAllTicketsView(UserView):
    '''
    Fetches all tickets and shows on dashboard.
    '''
    template_name = 'tickets/index.html'
    
    def __init__(self):
        UserView.__init__(self)
        self.error = AppMsgs.NOT_FETCH_TICKETS
        self.tickets_list = []
    
    def get(self, request):
        if checksession(AppMsgs.MBRKEY, request):
            login_time = getfromSession(AppMsgs.LOGIN_TIME_KEY, request)
            is_session_exceded = check_if_session_time_exceeds(login_time)
    #         Logout and redirect to login page
            if is_session_exceded:
                return HttpResponseRedirect(reverse('users:logout'))

            try:
                self.__fetch_all_tickets_list(request)
            except:
                pass
                    
            context = {AppMsgs.TICKETS_DICT_KEY:self.tickets_list, AppMsgs.ERROR:self.error}             
            return render(request, self.template_name, context)
        else:
            return HttpResponseRedirect(reverse('users:login'))    

    def __fetch_all_tickets_list(self, request):
        '''
        Get all ticket's list of customer
        @param request:
        '''
        if checksession(AppMsgs.FD_CUSTOMER_ID_KEY, request):
            fd_customer_id = getfromSession(AppMsgs.FD_CUSTOMER_ID_KEY, request)
            ticket_service_object = TicketService(request)
            ts_response = ticket_service_object.get_all_tickets_list(fd_customer_id)
            if ts_response[AppMsgs.MSG].lower() == AppStatus.SUCCESS:
                tickets_lst = ts_response[AppMsgs.RESP]
#                 Shows error if ticket's list is empty
                if len(tickets_lst) <= 0:
                    self.error = AppMsgs.DO_NOT_HAVE_OPEN_TICKETS
                else:
                    self.error = ''
                
                self.tickets_list = tickets_lst
        else:
            self.error = AppMsgs.DO_NOT_HAVE_OPEN_TICKETS
            self.tickets_list = []

tickets/views/CustomerTicketsView.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.AppServices.TicketService import TicketService
from airebeam_customer_portal.utils import checksession, getfromSession
from airebeam_customer_portal.utils import check_if_session_time_exceeds
from airebeam_customer_portal.enum import AppStatus
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView

class CustomerTicketsView(UserView):
    template_name = 'tickets/view_recent_tickets.html'
    
    def __init__(self):
        super(CustomerTicketsView, self).__init__()
        self.error = AppMsgs.NOT_FETCH_TICKETS
        self.tickets_list = []
    
    def get(self, request):
        if checksession(AppMsgs.MBRKEY, request):
            login_time = getfromSession(AppMsgs.LOGIN_TIME_KEY, request)
            is_session_exceded = check_if_session_time_exceeds(login_time)
    #         Logout and redirect to login page
            if is_session_exceded:
                return HttpResponseRedirect(reverse('users:logout'))
            self.error = AppMsgs.NOT_FETCH_TICKETS
            self.tickets_list = []
            try:    
                self.__fetch_specific_tickets(request)
            except:
                pass
            
            context = {AppMsgs.TICKET_LIST_KEY:self.tickets_list, AppMsgs.ERROR:self.error}             
            return render(request, self.template_name, context)              
        
        else:
            return HttpResponseRedirect(reverse('users:login'))

#    
    def __fetch_specific_tickets(self, request):
        '''
        Get all ticket's list of customer except CLOSED and RESOLVED tickets.
        @param request:
        '''
        if checksession(AppMsgs.FD_CUSTOMER_ID_KEY, request):
            fd_customer_id = getfromSession(AppMsgs.FD_CUSTOMER_ID_KEY, request)
            ticket_service_object = TicketService(request)
            ts_response = ticket_service_object.customer_specific_tickets(fd_customer_id)
            if ts_response[AppMsgs.MSG].lower() == AppStatus.SUCCESS:
                tickets_lst = ts_response[AppMsgs.RESP]
#                 Shows error if ticket's list is empty
                if len(tickets_lst) <= 0:
                    self.error = AppMsgs.DO_NOT_HAVE_OPEN_TICKETS
                else:
                    self.error = ''
                
                self.tickets_list = tickets_lst
            else:
                self.error = AppMsgs.DO_NOT_HAVE_OPEN_TICKETS
                self.tickets_list = []
        else:
            self.error = AppMsgs.DO_NOT_HAVE_OPEN_TICKETS
            self.tickets_list = []

        

tickets/views/ServiceDetailView.py
from django.shortcuts import render
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from tickets.models import Services

class ServiceDetailView(UserView):
    '''
    Fetches services details from db and shows on Account sevice's form.
    '''
    template_name = 'tickets/service_description.html'
    def get(self, request, service_id):
        service_field = Services.get_service_by_id(service_id)
        if service_field:
            context = {AppMsgs.SERVICE_FIELD_KEY: service_field}
            return render(request, self.template_name, context)
        else:
            context = {AppMsgs.SERVICE_FIELD_KEY: {}}
            return render(request, self.template_name, context)

tickets/views/ServicesView.py
from django.shortcuts import render
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from tickets.enum import ServicesGroup
from tickets.models import Services

class ServicesView(UserView):
    '''
    Fetches services from db and populate drop down with these on Account sevice's form.
    '''
    template_name = 'tickets/services.html'
    def get(self, request, group_id):
#         Group id must be in db
        if int(group_id) > ServicesGroup.NO_GROUP and int(group_id) <= ServicesGroup.EQUIPMENT_RENTAL:
            services = Services.get_services(group_id)
            context = {AppMsgs.SERVICES_KEY:services}
            return render(request, self.template_name, context)
        else:
            context = {}
            return render(request, self.template_name, context)

tickets/views/SubCategoriesView.py
from django.shortcuts import render
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from tickets.models import Categories

# This view fetches and return sub categories from db
class SubCategoriesView(UserView):
    '''
    Fetches and return sub categories from db on get support form.
    '''
    template_name = 'tickets/sub_categories.html'
    def get(self, request, sub_cat_id):
        if int(sub_cat_id) > 0 and int(sub_cat_id) <= 4:
            sub_categories = Categories.get_sub_categories(sub_cat_id)
            context = {AppMsgs.SUBCATEGORIES_KEY:sub_categories}
            return render(request, self.template_name, context)
        else:
            context = {}
            return render(request, self.template_name, context)

tickets/views/ThanksUpdatePaymentView.py
from django.shortcuts import render, redirect
from users.views.UserView import UserView
from airebeam_customer_portal.static_values import AppMsgs, CustomFields
from tickets.enum import TicketStatus, TicketPriority, group_id_mappings,\
    TicketType
from airebeam_customer_portal.ServicePayload import ServicePayload
import json
from airebeam_customer_portal.AppServices.TicketService import TicketService
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.utils import checksession, getfromSession, savesessiondata,\
    check_if_session_time_exceeds
from airebeam_customer_portal.AppServices.CustomerService import CustomerService

class ThanksUpdatePaymentView(UserView):
    form_template_name = 'tickets/thanks_update_payment.html'
    def __init__(self):
        self.error = ''
        
    def get(self, request):
        try:
            if checksession(AppMsgs.MBRKEY, request):
                login_time = getfromSession(AppMsgs.LOGIN_TIME_KEY, request)
                is_session_exceded = check_if_session_time_exceeds(login_time)
        #         Logout and redirect to login page
                if is_session_exceded:
                    return HttpResponseRedirect(reverse('users:logout'))
            context = {}
            return render(request, self.form_template_name, context)
        except Exception as e:
            return render(request, 'abcp_exception.html')

tickets/views/TicketConversationView.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.utils import checksession
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from airebeam_customer_portal.AppServices.ConversationService import ConversationService
from airebeam_customer_portal.enum import AppStatus

class TicketConversationView(UserView):
    '''
    Fetches all ticket's comments and notes.
    '''
    template_name = 'tickets/view_ticket_conversations.html'
    
    def __init__(self):
        UserView.__init__(self)
        self.error = AppMsgs.NOT_FETCH_TICKET_CONVERSATIONS
        self.ticket_id = ''
        self.conversations = []
    
    def get(self, request, ticket_id):
        if checksession(AppMsgs.MBRKEY, request):
            self.ticket_id = str(ticket_id)
            self.__fetch_ticket_conversations(request)
            
            context = {AppMsgs.CONVERSATIONS_KEY: self.conversations, AppMsgs.ERROR:self.error}
            return render(request, self.template_name, context)
                
        else:
            return HttpResponseRedirect(reverse('users:login'))

    def __fetch_ticket_conversations(self, request):
        '''
        Fetches ticket's all conversations.
        @param request:
        '''
        conversation_service_object = ConversationService(request)
        cs_response = conversation_service_object.get_conversations_by_ticket_id(self.ticket_id)
        if cs_response[AppMsgs.MSG].lower() == AppStatus.SUCCESS:
            self.conversations = cs_response[AppMsgs.RESP]
            self.error = ''
        else:
            self.conversations = []
    

tickets/templates/tickets/categories.html
{% extends 'base.html'  %}
	{% block page_name %} Get Support {% endblock %}
    {% block title %}Get Support{% endblock title %}

{% block head %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/summernote-bs3.css' %}" />
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/jquery.loadmask.min.js' %} "></script>
	<script type="text/javascript">
		var ua = navigator.userAgent.toLowerCase(); 
		if (ua.indexOf('safari') != -1) { 
		  if (ua.indexOf('chrome') > -1) {
			  // Chrome
		  } else {
			  document.write('<script src="//cdnjs.cloudflare.com/ajax/libs/webshim/1.16.0/dev/polyfiller.js"><\/script>');
		  }
		}
	</script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/summernote.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'tickets/main.js' %}"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
	<script src="{% static 'js/icheck/icheck.js' %}"></script>
	<script src="{% static 'js/daterangepicker.js' %}"></script>
	<script src="{% static 'js/moment.js' %}"></script>
{% endblock head %}


{% block content %}
<div id="ticket_submit_msg" class="alert no-display"></div>
<div class="row grid">
	<div class="col-md-12" id="div_3">
		    <div class="panel panel-primary abcp-category">
		        <div class="panel-heading">
		            <h2 class="panel-title acp-panel-title-color">
		             Create Ticket
		        </h2>
		    </div>
		    <div class="panel-body">
		        <div class="form-horizontal">
					{% if sub_categories %}
					<div id="sub_category_dd">
						<div class="form-group">
							<label class="col-lg-3 control-label">Select Category</label>
							<div class="col-lg-8">
								<select class="form-control" id="sub_categories_select" onchange="show_form('sub_categories_select')">
									<option value="0">Select</option>
									{%for sc in sub_categories%}
										<option value="{{sc.id}}">{{sc.name}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
					</div>
					<div id="dynamic_form"> </div>
					{% endif %}
				</div>
		    </div>
		    <!-- /panel body -->
		</div>
	</div>
</div>

{% endblock %}

tickets/templates/tickets/create_form.html
<form id="create_ticket_form" action="{% url 'tickets:get_form' sub_cat_id %}" method="post">
{% csrf_token %}
<input id="id_missing_card_fields" type="hidden" value="{{missing_card_fields | lower }}" />
<input id="id_missing_check_fields" type="hidden" value="{{missing_check_fields | lower }}" />
{% for field in form.visible_fields %}
	{% if field.name in card_fields %}
		<div class="form-group abcp-card hide-init">
	{% elif field.name in check_fields %}
		<div class="form-group abcp-check hide-init">
	{% elif field.name == 'payment_amount' %}
		<div class="form-group abcp-card-account-fields">
	{% elif field.name == 'card_number' or field.name == 'card_expiry' or field.name == 'card_cvv' %}
		<div class="form-group abcp-card-fields">
	{% elif field.name == 'cable_length' %}
		<div class="form-group abcp-cable-length hide-init">
	{% elif field.name == 'new_payment_method' %}
		<div class="form-group abcp-payment-method">
	{% else %}
		<div class="form-group">
	{% endif %}
	
	{% if field.name == 'description' %}
			<label class="col-lg-3 control-label">{{field.label_tag}}</label>
	        <div class="col-lg-8">
            	<div id="description"></div>
            </div>
	        <input id="description_value" name="{{field.name}}" type="hidden" />
	{% elif 'date' in field.name and 'expiration_date_if_card' != field.name %}
		<label class="col-lg-3 control-label">{{ field.label_tag  }}</label>
                <div class="col-lg-8">
	                	<div class="input-prepend input-group">
							<span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
							<input type="text" style="width: 200px" name="{{field.name}}" class="form-control abcp-date-control"
							 />
						</div>
			   </div>
			   
		
		
	{% else %}
		{% if field.name in check_fields and missing_check_fields %}
			<label class="col-lg-3 control-label"></label>
			<div class="col-lg-8"></div>
		
		{% elif field.name in card_fields and missing_card_fields %}
			<label class="col-lg-3 control-label"></label>
			<div class="col-lg-8"></div>
			
		{% else %}
			<label class="col-lg-3 control-label">{{ field.label_tag  }}</label>
			<div class="col-lg-8">{{ field }}</div>
		{% endif %}			
		
		{% if 'i_agree_to_pay_through_my_card_on_file' == field.name %}			   
			<div class="clearfix"></div>
			<br/>		
			<div class="col-lg-8 col-lg-offset-3">
				The details of your card on file are displayed above. 
				To use this card to make the payment, click the check box and click Submit. 
				To update the card on file, click <b><a href="{% url "tickets:generate_up_ticket" %}">HERE</a></b> to submit a ticket
			</div>
		
		{% elif 'i_agree_to_pay_through_my_echeck_on_file' == field.name %}			   
			<div class="clearfix"></div>
			<br/>		
			<div class="col-lg-8 col-lg-offset-3">
				The details of your E-check on file are displayed above. 
				To use this E-check to make the payment, click the check box and click Submit. 
				To update the E-check on file, click <b><a href="{% url "tickets:generate_up_ticket" %}?echeck=1">HERE</a></b> to submit a ticket
			</div>
			
		{% elif 'i_agree_to_modify_my_card_payment_details' == field.name %}			   
			<div class="clearfix"></div>
			<br/>		
			<div class="col-lg-8 col-lg-offset-3">
				The credit card details that we have on file are shown above. 
				Please confirm that you wish to update this information by selecting the checkbox and then click submit. 
				A customer service representative will call you shortly.
			</div>
			
		{% elif 'i_agree_to_modify_my_echeck_payment_details' == field.name %}			   
			<div class="clearfix"></div>
			<br/>		
			<div class="col-lg-8 col-lg-offset-3">
				The E-check details that we have on file are shown above. 
				Please confirm that you wish to update this information by selecting the checkbox and then click submit. 
				A customer service representative will call you shortly.
			</div>
		{% endif %}
		
	{% endif %}
		
	</div>
{% endfor %}
	<div id="id_missing_card_field_msg_div" class="form-group no-display">
		<label class="col-lg-3 control-label"><label ></label></label>
		<div class="col-lg-8">
			Dear Customer we are sorry to inform you that we do not have your Credit Card details with us. 
			Please Click <b><a href="{% url "tickets:generate_up_ticket" %}">HERE</a></b> to submit a ticket for updating your payment method details.
		</div>
	</div>
	
	<div id="id_missing_check_field_msg_div" class="form-group no-display">
		<label class="col-lg-3 control-label"><label ></label></label>
		<div class="col-lg-8">
			Dear Customer we are sorry to inform you that we do not have your E-check Account details with us. 
			Please Click <b><a href="{% url "tickets:generate_up_ticket" %}?echeck=1">HERE</a></b> to submit a ticket for 
			updating your payment method details.
		</div>
	</div>

	<div id="one_time_cc_msg_div" class="form-group no-display">
		<label class="col-lg-3 control-label"><label ></label></label>
		<div class="col-lg-8">
			Thank you for choosing new one time payment method. 
			Our customer service representative will call you shortly to receive and update your new credit card details.
		</div>
	</div>
	
	<div id="one_time_echeck_msg_div" class="form-group no-display">
		<label class="col-lg-3 control-label"><label ></label></label>
		<div class="col-lg-8">
			Thank you for choosing new one time payment method. 
			Our customer service representative will call you shortly to receive and update your new E-check details.
		</div>
	</div>
	
	
	<div class="form-group" id="desired_services_div"></div>
	<div id="service_description"></div>
	<div id="new_equipment_info" class="hide-init">
		<div class="form-group">
				<label class="col-lg-3 control-label"> Length : </label>
				<div id="length_div" class="col-lg-8 abcp-align-fields-with-label">Foot</div>
		</div>
		<div class="form-group">
				<label class="col-lg-3 control-label"> Cost Per Foot : </label>
				<div class="col-lg-8 abcp-align-fields-with-label">$1.10</div>
		</div>
		<div class="form-group">
				<label class="col-lg-3 control-label"> Total Cost : </label>
				<div id="equipment_total_cost" class="col-lg-8 abcp-align-fields-with-label">$</div>
		</div>
		
	</div>
		
	

{% for field in form.hidden_fields  %}
		{{ field }}
{% endfor %}

<input id="selected_parent_category" name="selected_parent_category" type="hidden" />
    <div class="row grid">
		<div id="div_3">
			<div class="panel panel-primary">
                    <div class="form-horizontal">
                        	<label class="col-lg-3 control-label"></label>
                            <div class="acp-reply-section col-lg-8">
                            	<div class="cbp_tmlabel acp-create-form">
                                	<input type="submit" value="Submit" style="display:none;">
                                	<span id="id_submit_container">
                                    	<button type="button" class="btn btn-reply btn-lg abcp-submit-btn" onclick="submit_form()">Submit</button>
                                    </span>
                                    <button type="button" class="btn btn-cancel btn-lg" onclick="go_to_dashboard()">Cancel</button>
                                </div>
                            </div>
                    </div>
           </div>
        </div>
    </div>
</form>

{% load static %}
<script type="text/javascript" src="{% static 'tickets/create_form.js' %}" ></script>

tickets/templates/tickets/index.html
{% if tickets_dict %}
        	<div class="table-responsive">
                <table class="table table-striped" id="all_tickets">
					
						<thead>
                        <tr> 
                            <th>Ticket#</th>
							<th>Status</th>
							<th>Subject</th>
							<th class="abcp-lastupdated">Last Updated</th>	
                        </tr>
                        </thead>
                        <tbody>
					{%for ticket in tickets_dict%}
						<tr id="ticket_tr_{{ticket.id}}" class="{% if ticket.highlight == True %}abcp-highlight{% endif %}">
							<td>{{ticket.id}}</td>
							<td>{{ticket.status_text}}</td>
							<td>
								<a class="page_links" id="ticket_link_{{ticket.id}}" href="{% url 'tickets:view_ticket' ticket.id %}">
						        		{{ ticket.subject }}
						        </a>
							
							</td>
							<td class="abcp-lastupdated">{{ticket.updated_at|date:"F d, Y"}} {{ticket.updated_at|date:"h:i A"}}</td>
						</tr>
				    {% endfor %}
                   </tbody>
				</table>
                </div>
{% else %}
	<h3 class="acp-center-align">{{error}}</h3>
{% endif %}

{% load static %}
<script type="text/javascript" src="{% static 'tickets/acp_datatable_config.js' %}" ></script>

tickets/templates/tickets/view_recent_tickets.html
{% if tickets_list %}
</style>
<div class="table-responsive">
	
	<table class="table table-striped" id="recent_tickets_table">
		<thead>
        <tr> 
			<th>Ticket#</th>
			<th>Status</th>
			<th>Subject</th>
			<th class="abcp-lastupdated">Last Updated</th>	
		</tr>
		</thead>
		<tbody>
		{%for ticket in tickets_list %}
			<tr id="ticket_tr_{{ticket.id}}"  class="{% if ticket.highlight == True %}abcp-highlight{% endif %}">
				<td>{{ticket.id}}</td>
				<td>{{ticket.status_text}}</td>
				<td>
						<a class="page_links" id="ticket_link_{{ticket.id}}" href="{% url 'tickets:view_ticket' ticket.id %}">
				        		
				        			{{ ticket.subject }}
				        		
				        </a>				    				
				</td>
				<td class="abcp-lastupdated">{{ticket.updated_at|date:"F d, Y"}} {{ticket.updated_at|date:"h:i A"}}</td>
				
			</tr>
		{% endfor %}
        </tbody>
	</table>
 </div>
{% else %}
	<h3 class="acp-center-align">{{error}}</h3>
{% endif %}

{% load static %}
<script type="text/javascript" src="{% static 'tickets/acp_datatable_config.js' %}" ></script>