airebeam_customer_portal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users.views.Error404View import Error404View
handler404 = Error404View.as_view()

urlpatterns = [
    url(r'^change_password/', include('change_password.urls')),
    url(r'^reset_password/', include('reset_password.urls')),
    url(r'^terms/', include('terms_and_conditions.urls')),
    url(r'^operator/', include('agents.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^forgot_password/', include('forgot_password.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^radiostats/', include('radiostats.urls')),
    url(r'^mbr_online_check/', include('mbr_online_check.urls')),
    url(r'^tickets/', include('tickets.urls')),
    url(r'^', include('dashboard.urls')),

] 

forgot_password/urls.py
from django.conf.urls import url

from forgot_password.views.FpFormView import FpFormView

app_name = 'forgot_password'
urlpatterns = [
	url(r'$', FpFormView.as_view(), name = 'index'),
]

users/urls.py
from django.conf.urls import url

from users import views_function
from users.views.LoginFormView import LoginFormView
from users.views.LogoutView import LogoutView

app_name = 'users'
urlpatterns = [
	url(r'^loggedin$', views_function.loggedin, name = 'loggedin'),
	url(r'^login$', LoginFormView.as_view(), name='login'),
	url(r'^logout$', LogoutView.as_view(), name = 'logout'),
	url(r'^extend_base_view$', views_function.extend_base_view, name = 'extend_base_view'),
	url(r'^get_pdf$', views_function.get_pdf, name = 'get_pdf'),	
]

forgot_password/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

forgot_password/forms.py
from django import forms
 
class FpForm(forms.Form):
    mbr_checkbox = forms.BooleanField(label='I do not remember my account number', required=True, 
                                      widget=forms.CheckboxInput(attrs={'class':'square-input'}))
    address_text = forms.CharField(max_length=100, label='Address 1', required=False, 
                          widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address 1'}))
    phone_number_text = forms.CharField(max_length=100, label='Home Phone Number', required=False, 
                          widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Home Phone Number'}))
    last_four_cc_digit_text = forms.CharField(max_length=100, label='Last 4 Credit Card Digits', required=True, 
                          widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last 4 Credit Card Digits'}))

forgot_password/views/FpFormView.py
from django.shortcuts import render, redirect
from forgot_password.forms import FpForm
from airebeam_customer_portal.enum import user_access_level, ForgotPasswordStatus, AppStatus,\
    AjaxCallStatus, PasswordResetMethod, SHALLOWORRESET
from airebeam_customer_portal.utils import savesessiondata, checksession
from mbr_online_check.models import mbrDetail
from airebeam_customer_portal.AppServices.CustomerService import CustomerService
import datetime
from airebeam_customer_portal.AppServices.ForgotPasswordService import ForgotPasswordService
import base64
from airebeam_customer_portal.static_values import AppMsgs, MbrDetailKeys,\
    CustomerInfo
from airebeam_customer_portal.ServicePayload import ServicePayload
from users.views.UserView import UserView
from airebeam_customer_portal.AppServices.CustomerInfoService import CustomerInfoService
from airebeam_customer_portal.AppServices.LoginService import LoginService

class FpFormView(UserView):
    '''
    Forgot password view for customers.
    '''
    form_class = FpForm
    form_template_name = 'forgot_password/fp_form.html'
    
    def __init__(self):
        self.error = ''
        self.mbr = ''
        self.mbr_checkbox = ''
        self.address_text = ''
        self.phone_number_text = ''
        self.last_four_cc_digit_text = ''
        self.customer_info_obj = ''
        
    def get(self, request):
        '''
        Shows forgot password form.
        @param request:
        '''
        try:
            if checksession(AppMsgs.MBRKEY,request) or \
            self.get_agent_username() is not None:
                return redirect('dashboard:index')
            self.error = ''
            form = self.form_class()
            return render(request, self.form_template_name, {
                    AppMsgs.FORMKEY: form, AppMsgs.ERROR: self.error
                })
        except:
            return render(request, 'abcp_exception.html')
        
    def post(self, request):
        '''
        Processes form and redirect to view where customer can request for reset password
        through an email, sms or customer can select either by email or sms.
        @param request:
        '''
        try:
            self.error = ''
            form = self.form_class(request.POST)
            if form.is_valid():
                self.__set_form_fields(form)
                reset_or_dashboard = self.__login_customer_into_portal()
                if(reset_or_dashboard == SHALLOWORRESET.DASHBOARD):
                    return redirect('dashboard:index')
                elif (reset_or_dashboard == SHALLOWORRESET.RESET):
                    redirect_method = self.redirect_to_reset_approval()
                    if redirect_method == PasswordResetMethod.BOTH_EMAIL_CELLPHONE:
#         Redirect to reset method where we offer both email and cellphone
                        return redirect('reset_password:reset_method')
                        pass
                    elif redirect_method == PasswordResetMethod.EMAIL:
#         Redirect to reset method where we offer email
                        return redirect('reset_password:email_approval')
                        pass
                    elif redirect_method == PasswordResetMethod.CELLPHONE:
#         Redirect to reset method where we offer cellphone
                        return redirect('reset_password:sms_approval')
                        pass

            return render(request, self.form_template_name, {
                    AppMsgs.FORMKEY: form, AppMsgs.ERROR: self.error
                })
            
        except:
            return render(request, 'abcp_exception.html')
        
    def redirect_to_reset_approval(self):
        '''
        Method returns reset password by email if it has email, returns reset by sms if it 
        has valid cell phone number and returns both email and sms if it has both.
        '''
        if self.customer_info_obj[CustomerInfo.EMAIL] != '0' and self.customer_info_obj[CustomerInfo.PHONEHOME] != '' \
        and self.customer_info_obj[CustomerInfo.IS_PHONEHOME_LANDLINE] == '0':
            return PasswordResetMethod.BOTH_EMAIL_CELLPHONE
        
        elif self.customer_info_obj[CustomerInfo.EMAIL] != '0':
            return PasswordResetMethod.EMAIL
        
        elif self.customer_info_obj[CustomerInfo.PHONEHOME] != '' \
        and self.customer_info_obj[CustomerInfo.IS_PHONEHOME_LANDLINE] == '0':
            return PasswordResetMethod.CELLPHONE

    def __set_form_fields(self, form):
        '''
        Method sets form attributes which is given by customer
        @param form:
        '''
        self.mbr_checkbox = form.cleaned_data[AppMsgs.MBR_CHECKBOX]
        self.address_text = form.cleaned_data[AppMsgs.ADDRESS_TEXT]
        self.address_text = base64.b64encode(self.address_text)
        self.phone_number_text = form.cleaned_data[AppMsgs.PHONE_NUMBER_TEXT]
        self.last_four_cc_digit_text = form.cleaned_data[AppMsgs.LAST_FOUR_CC_DIGIT_TEXT]
        
    def __login_customer_into_portal(self):
        '''
        Method logins customer if they do not have email and cell phone number and
        they provide valid address or home phone number and valid credit card 
        last four digits.
        '''
        payload = ServicePayload.get_forgot_password_service_payload(self.address_text, 
                                                                             self.phone_number_text, 
                                                                             self.last_four_cc_digit_text)
        fp_service_object = ForgotPasswordService()
        fp_response = fp_service_object.call_service(payload)
        response_msg = fp_response[AppMsgs.MSG].lower()
        response_status = int(fp_response[AppMsgs.RESP][AppMsgs.STATUS_KEY])
        if response_msg == AppStatus.SUCCESS and\
        response_status == ForgotPasswordStatus.SUCCESS:
#         Call customer info service and check customer has email/cellphone
            response_obj = fp_response[AppMsgs.RESP]
            self.mbr = fp_response[AppMsgs.RESP][MbrDetailKeys.MBR_KEY]
            
            ci_object = CustomerInfoService()
            ci_payload = ServicePayload.get_customer_info_service_payload(self.mbr)
            ci_response = ci_object.call_service(ci_payload)
            customer_info = ci_response[AppMsgs.RESP][CustomerInfo.CUSTOMER]
            self.set_customer_info(customer_info)
            if customer_info[CustomerInfo.EMAIL] != '0' or (customer_info[CustomerInfo.PHONEHOME] != '' \
            and customer_info[CustomerInfo.IS_PHONEHOME_LANDLINE] == '0'):
#                 Redirect to page where we offer resetting password from both email and cellphone
                self.customer_info_obj = customer_info
                return SHALLOWORRESET.RESET
            else:
                self.set_force_reset_pass(customer_info[CustomerInfo.IS_PASSWORD_RESET])
                user_acl = user_access_level[AppMsgs.SHALLOW_KEY]
                LoginService.set_customer_data(self, response_obj, user_acl, self.mbr)
                mbr = LoginService.fetch_mbr_details(self, self.mbr)
                self.request.session[AppMsgs.USERNAME_KEY] = mbr.detail[MbrDetailKeys.FIRSTNAME_KEY]
                LoginService.search_customer_on_fd_by_phone(self, self.mbr)
                return SHALLOWORRESET.DASHBOARD

        elif response_msg == AppStatus.SUCCESS and\
            response_status == ForgotPasswordStatus.MISSING_REQUIRED_PARAMS:
            self.error = fp_response[AppMsgs.RESP][AppMsgs.MESSAGE]
        elif response_msg == AppStatus.SUCCESS and\
            response_status == ForgotPasswordStatus.MBR_NOT_EXIST:
            self.error = AppMsgs.ACCOUNT_NOT_FOUND
        elif response_msg == AppStatus.SUCCESS and\
            response_status == ForgotPasswordStatus.PHONE_ADDRESS_MISSING:
            self.error = AppMsgs.PHONE_AND_ADDRESS_MISSING
        elif response_msg == AppStatus.SUCCESS and\
            response_status == ForgotPasswordStatus.CREDIT_CARD_MISSING:
            self.error = fp_response[AppMsgs.RESP][AppMsgs.MESSAGE]
        else:
            pass
        
        return SHALLOWORRESET.ERROR

forgot_password/templates/forgot_password/fp_form.html
<title>Forgot Password or Account Number</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/icheck/icheck.js' %}"></script>
	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/polaris.css' %}" />
	<script type="text/javascript" src="{% static 'forgot_password/main.js' %}"></script>
	<!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />


	<div class="login-page">
		{% include "login_page_header.html" %}
		<div class="form-section">
			<div class="container">

				<div class="form-inputs">
					<h4>Forgot Password or Account Number?</h4>
					
					<form id="fp_form" action="" method="post">{% csrf_token %}
						<div class="acp-fp-errors"> {{error}} </div>
						<div class="input-group acp-inputs acp-inputs-width">
							{{ form.address_text  }}
							<span class="input-group-addon"><i class="fa fa-home"></i></span>
						</div>
						<div class="acp-fp-errors">
							{{ form.address_text.errors.as_text }}
						</div>
						<div class="input-group acp-inputs acp-inputs-width">
							{{ form.phone_number_text  }}
							<span class="input-group-addon"><i class="fa fa-phone"></i></span>
						</div>
						<div class="acp-fp-errors">
							{{ form.phone_number_text.errors.as_text }}
						</div>
						<div class="input-group acp-inputs acp-inputs-width">
							{{ form.last_four_cc_digit_text  }}
							<span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
						</div>
						<div class="acp-fp-errors">
							{{ form.last_four_cc_digit_text.errors.as_text }}
						</div>
                        
						<div class="input-group acp-inputs acp-inputs-width">
                        	{{ form.mbr_checkbox }} <label for="id_mbr_checkbox" class="acp-fp-check-text">{{ form.mbr_checkbox.label}}</label>
						</div>
						<div class="acp-fp-errors">
							{{ form.mbr_checkbox.errors.as_text }}
						</div>
	    					<div>
	    						
								<input id="fp_submit_btn" onclick="submit_form()" type='button' value='Submit' class="btn btn-info pull-right" />
                                <input id="return_to_login_btn" onclick="return_to_login()" type="button" value="Return to login" class="btn btn-info">
								
							</div>
							
							<button class="acp-forgot-checkbox" id="chk_btn" type="button"></button>
							
							
					</form>

			</div>				
			</div>
		</div><!--emd of form-section-->
		{% include "footer_before_login.html" %}
	</div><!--cnd of Forgot password page-->