airebeam_customer_portal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users.views.Error404View import Error404View
handler404 = Error404View.as_view()

urlpatterns = [
    url(r'^change_password/', include('change_password.urls')),
    url(r'^reset_password/', include('reset_password.urls')),
    url(r'^terms/', include('terms_and_conditions.urls')),
    url(r'^operator/', include('agents.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^forgot_password/', include('forgot_password.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^radiostats/', include('radiostats.urls')),
    url(r'^mbr_online_check/', include('mbr_online_check.urls')),
    url(r'^tickets/', include('tickets.urls')),
    url(r'^', include('dashboard.urls')),

] 

reset_password/urls.py
from django.conf.urls import url

from reset_password.views.EmailApprovalView import EmailApprovalView
from reset_password.views.SmsApprovalView import SmsApprovalView
from reset_password.views.ExpiredLinkView import ExpiredLinkView
from reset_password.views.CallApprovalView import CallApprovalView
from reset_password.views.ResetPasswordView import ResetPasswordView
from reset_password.views.SendEmailApprovalService import SendEmailApprovalService
from reset_password.views.ResetPassService import ResetPassService
from reset_password.views.SendSmsApprovalService import SendSmsApprovalService
from reset_password.views.VerifyCodeService import VerifyCodeService
from reset_password.views.ChooseResetMethodView import ChooseResetMethodView
from reset_password.views.UserHasContactView import UserHasContactView
from reset_password.views.CustomerContactInfoView import CustomerContactInfoView
from reset_password.views.ThanksSubmitInfoView import ThanksSubmitInfoView

app_name = 'reset_password'
urlpatterns = [
    url(r'email_approval$', EmailApprovalView.as_view(), name = 'email_approval'),
    url(r'sms_approval$', SmsApprovalView.as_view(), name = 'sms_approval'),
    url(r'link_expired$', ExpiredLinkView.as_view(), name = 'link_expired'),
    url(r'call_approval$', CallApprovalView.as_view(), name = 'call_approval'),
    url(r'reset_view$', ResetPasswordView.as_view(), name = 'reset_view'),
    url(r'send_reset_pass_email$', SendEmailApprovalService.as_view(), name = 'send_reset_pass_email'),
    url(r'reset_pass_service$', ResetPassService.as_view(), name = 'reset_pass_service'),
    url(r'send_reset_pass_sms$', SendSmsApprovalService.as_view(), name = 'send_reset_pass_sms'),
    url(r'verify_sms_code$', VerifyCodeService.as_view(), name = 'verify_sms_code'),
    url(r'reset_method$', ChooseResetMethodView.as_view(), name = 'reset_method'),
    url(r'user_has_contact$', UserHasContactView.as_view(), name = 'user_has_contact'),
    url(r'customer_contact_info$', CustomerContactInfoView.as_view(), name = 'customer_contact_info'),
    url(r'thanks_submit_info$', ThanksSubmitInfoView.as_view(), name = 'thanks_submit_info'),
]

users/urls.py
from django.conf.urls import url

from users import views_function
from users.views.LoginFormView import LoginFormView
from users.views.LogoutView import LogoutView

app_name = 'users'
urlpatterns = [
	url(r'^loggedin$', views_function.loggedin, name = 'loggedin'),
	url(r'^login$', LoginFormView.as_view(), name='login'),
	url(r'^logout$', LogoutView.as_view(), name = 'logout'),
	url(r'^extend_base_view$', views_function.extend_base_view, name = 'extend_base_view'),
	url(r'^get_pdf$', views_function.get_pdf, name = 'get_pdf'),	
]

reset_password/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tickets/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Categories(models.Model):
	name = models.CharField(max_length=100)
	parent_id = models.IntegerField()
	date = models.DateTimeField(auto_now_add=True)

	@classmethod
	def get_parent_categories(self):
		return Categories.objects.filter(parent_id=0)

	@classmethod
	def get_sub_categories(self, cat_id):
		return Categories.objects.filter(parent_id=cat_id)

	class Meta:
		db_table = "categories"

class Forms(models.Model):
	name = models.CharField(max_length=100)
	fields = models.CharField(max_length=64400)
	cat_id = models.ForeignKey(Categories, on_delete=models.CASCADE)
	fd_group = models.IntegerField(default=0)
	fd_type = models.CharField(max_length=100, default='')
	fd_priority = models.IntegerField(default=2)
	
	@classmethod
	def get_form(self, form_id):
		return Forms.objects.filter(cat_id_id=form_id)
	
	class Meta:
		db_table = "forms"
		
class Additional_Subcat_Fields(models.Model):
	fields = models.CharField(max_length=64400)
	sub_cat_id = models.ForeignKey(Categories, on_delete=models.CASCADE)
	
	@classmethod
	def get_by_subcat_id(self, sub_cat_id):
		return Additional_Subcat_Fields.objects.filter(sub_cat_id=sub_cat_id)
	
	class Meta:
		db_table = "additional_subcat_fields"
		
class Services(models.Model):
	name = models.CharField(max_length=1024)
	group_id = models.IntegerField()
	date = models.DateTimeField(auto_now_add=True)
	cost = models.CharField(default='', max_length=9)
	tax = models.CharField(default='', max_length=50)
	description = models.CharField(default='', max_length=1024)
	setup_charge = models.CharField(default='', max_length=50)
	
	@classmethod
	def get_groups(self):
		return Services.objects.filter(group_id=0)
	
	@classmethod
	def get_services(self, grp_id):
		return Services.objects.filter(group_id=grp_id)
	
	@classmethod
	def get_service_by_id(self, id):
		return Services.objects.get(pk=id)
	
	
	class Meta:
		db_table = "services"
	

contact_us/forms.py
from django import forms
from airebeam_customer_portal.static_values import CustomerInfo
 
class ContactUsForm(forms.Form):
    name = forms.BooleanField(label='Name', 
                                      widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name'}))
    email = forms.EmailField(max_length=100, label=CustomerInfo.EMAIL, 
                          widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':CustomerInfo.EMAIL}))
    subject = forms.CharField(max_length=100, label='Subject',  
                          widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Subject'}))

users/forms.py
from django import forms
import json
from airebeam_customer_portal.enum import form_fields_map
 
class LoginForm(forms.Form):
    mbr = forms.CharField(max_length=100, label='Account Number', 
                          widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Account Number'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
  

def get_class( self, kls ):
		parts = kls.split('.')
		module = ".".join(parts[:-1])
		m = __import__( module )
		for comp in parts[1:]:
			m = getattr(m, comp)            
		return m

reset_password/views/CallApprovalView.py
from django.shortcuts import render, redirect
from users.views.UserView import UserView
from airebeam_customer_portal.static_values import AppMsgs, CustomFields,\
    MbrDetailKeys, CustomerInfo
from tickets.enum import TicketStatus, TicketPriority, group_id_mappings,\
    TicketType
from airebeam_customer_portal.ServicePayload import ServicePayload
import json
from airebeam_customer_portal.AppServices.TicketService import TicketService
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from airebeam_customer_portal.utils import checksession, getfromSession, savesessiondata
from airebeam_customer_portal.AppServices.CustomerService import CustomerService
from airebeam_customer_portal import config
from airebeam_customer_portal.enum import AppStatus

class CallApprovalView(UserView):
    form_template_name = 'reset_password/call_approval.html'
    def __init__(self):
        self.error = ''
        
        
    def get(self, request):
        try:
            customer_info_obj = self.get_customer_info()
            if customer_info_obj is not None:
                phone_home = customer_info_obj[CustomerInfo.PHONEHOME]
                context = {AppMsgs.PHONE_HOME_KEY: phone_home}
                
                return render(request, self.form_template_name, context)
            else:
                return HttpResponseRedirect(reverse('forgot_password:index'))
        except:
            return render(request, 'abcp_exception.html')
        
    def post(self, request):
        try:
            mbr = getfromSession(AppMsgs.MBRKEY, request)
            if not checksession(AppMsgs.FD_CUSTOMER_ID_KEY, request):
                mbr_detail = getfromSession(AppMsgs.MBR_DETAIL_KEY,request)
                name = mbr_detail[MbrDetailKeys.FIRSTNAME_KEY] + ' ' + mbr_detail[MbrDetailKeys.LASTNAME_KEY]
                email =  mbr_detail[MbrDetailKeys.EMAIL_KEY]
                address = mbr_detail[MbrDetailKeys.ADDRESS1_KEY]
                phone_home = mbr_detail[MbrDetailKeys.PHONEHOME_KEY]
                mobile = mbr_detail[MbrDetailKeys.PHONEHOME_KEY]
                payload = ServicePayload.get_create_customer_payload(name, mbr, email, address, phone_home, mobile)
                payload = json.dumps(payload)
                customer_service_object = CustomerService()
                cs_response = customer_service_object.create_customer(payload)
                if cs_response[AppMsgs.MSG].lower() == AppStatus.SUCCESS:
                    customer = cs_response[AppMsgs.RESP]
                    savedata = customer[AppMsgs.ID_KEY]
                    savesessiondata(AppMsgs.FD_CUSTOMER_ID_KEY, savedata, request)
                else:
                    url = reverse('dashboard:index')
                    url += '?s=-1'
                    return HttpResponseRedirect(url)
                
            if checksession(AppMsgs.FD_CUSTOMER_ID_KEY, request):
                customer_info_obj = self.get_customer_info()
                ticket_body = customer_info_obj[CustomerInfo.CUSTOMER_NAME] + ' ' + AppMsgs.CALL_APPROVAL_TICKET_BODY
                TestStr = config.TestStr
                ticket_title = AppMsgs.ACCOUNT_CHANGE
                mbr_detail = getfromSession(AppMsgs.MBR_DETAIL_KEY,request)
                ticket_subject = '{0}{1}, {2}, {3} - {4}'.format(TestStr, 
                                                           mbr_detail[MbrDetailKeys.MBR_KEY], 
                                                           mbr_detail[MbrDetailKeys.LASTNAME_KEY], 
                                                           mbr_detail[MbrDetailKeys.FIRSTNAME_KEY],
                                                           ticket_title)
                status = TicketStatus.OPEN
                fd_priority = TicketPriority.LOW
                fd_group = group_id_mappings[AppMsgs.SUPPORT]
                fd_type = TicketType.PORTAL_SETUP
                fd_customer_id = getfromSession(AppMsgs.FD_CUSTOMER_ID_KEY, request)
                custom_fields_obj = CustomFields()
                custom_fields = custom_fields_obj.get_mbr_to_no_support_payload(mbr)
                payload = ServicePayload.get_create_ticket_payload(fd_group, fd_type, fd_priority, 
                                                                   ticket_body, ticket_subject, status, 
                                                                   fd_customer_id, custom_fields)
                
                payload = json.dumps(payload)
                ticket_service_object = TicketService(request)
                ts_response = ticket_service_object.create_ticket(payload)
                url = reverse('dashboard:index')
                if ts_response[AppMsgs.MSG].lower() == AppStatus.SUCCESS:
                    url += '?s=2'
                    response_dict = json.dumps(ts_response)
                    return redirect(url)
                else:
                    url += '?s=0'
                    return redirect(url)
            
        except Exception as e:
            return render(request, 'abcp_exception.html')

reset_password/views/ChooseResetMethodView.py
from django.shortcuts import render
from users.views.UserView import UserView
from airebeam_customer_portal.static_values import AppMsgs
from airebeam_customer_portal.utils import checksession
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class ChooseResetMethodView(UserView):
    form_template_name = 'reset_password/choose_reset_method.html'
    def __init__(self):
        self.error = ''
        
        
    def get(self, request):
        try:
            customer_info_obj = self.get_customer_info()
            if customer_info_obj is not None:
                context = {}
                return render(request, self.form_template_name, context)
            else:
                return HttpResponseRedirect(reverse('forgot_password:index'))
        except:
            return render(request, 'abcp_exception.html')

reset_password/views/EmailApprovalView.py
from django.shortcuts import render
from users.views.UserView import UserView
from airebeam_customer_portal.static_values import AppMsgs, CustomerInfo
from airebeam_customer_portal.utils import checksession
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class EmailApprovalView(UserView):
    form_template_name = 'reset_password/email_approval.html'
    def __init__(self):
        self.error = ''
        
        
    def get(self, request):
        try:
            customer_info_obj = self.get_customer_info()
            if customer_info_obj is not None:
                email = customer_info_obj[CustomerInfo.EMAIL]
                email_array = email.split('@')
                email_first_part = email_array[0]
                masked_email = email_first_part[0:2] + '******' + email_first_part[-2:] + '@' +  email_array[1]
                context = {AppMsgs.CUSTOMER_EMAIL_KEY: masked_email, 
                           AppMsgs.THANK_YOU_BACK_KEY: AppMsgs.THANK_YOU_NO_LOGIN_TEXT}
                
                return render(request, self.form_template_name, context)
            else:
                return HttpResponseRedirect(reverse('forgot_password:index'))
        except:
            return render(request, 'abcp_exception.html')

reset_password/views/ExpiredLinkView.py
from django.shortcuts import render
from users.views.UserView import UserView
from airebeam_customer_portal.static_values import AppMsgs
from airebeam_customer_portal.utils import checksession
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class ExpiredLinkView(UserView):
    form_template_name = 'reset_password/expired_link.html'
    def __init__(self):
        self.error = ''
        
        
    def get(self, request):
        try:
            customer_info_obj = self.get_customer_info()
            if customer_info_obj is not None:
                context = {}
                return render(request, self.form_template_name, context)
            else:
                return HttpResponseRedirect(reverse('forgot_password:index'))
        except:
            return render(request, 'abcp_exception.html')

reset_password/views/ResetPassService.py
from django.http import HttpResponse
import json
from airebeam_customer_portal.utils import getfromSession, savesessiondata, \
clear_user_data_keys
from airebeam_customer_portal.utils import check_if_session_time_exceeds
from airebeam_customer_portal.static_values import AppMsgs
from users.views.UserView import UserView
from mbr_online_check.models import mbrDetail
from airebeam_customer_portal.AppServices.CustomerService import CustomerService
from warnings import catch_warnings
from airebeam_customer_portal.AppServices.SendEmailService import SendEmailService
from airebeam_customer_portal.enum import SendEmailStatus, Protocol
from airebeam_customer_portal.AppServices.UpdatePasswordService import UpdatePasswordService
from airebeam_customer_portal.ServicePayload import ServicePayload
import base64
from airebeam_customer_portal.SimpleNamespace import SimpleNamespace
import ast

class ResetPassService(UserView):
    def __init__(self):
        pass
    
    def post(self, request):
        try:
            request_body = request.POST
            mbr = request_body[AppMsgs.MBRKEY]
            password = base64.b64encode(request_body[AppMsgs.PASSWORD_KEY])
            key = request_body[AppMsgs.RESET_PASS_KEY]
            medium = request_body[AppMsgs.RESET_PASS_MEDIUM]
            payload = ServicePayload.get_update_password_payload(mbr, password, key, medium)
            reset_pass_obj = UpdatePasswordService()
            reset_pass_response = reset_pass_obj.call_service(payload)
            reset_pass_status = int(reset_pass_response[AppMsgs.RESP][AppMsgs.STATUS_KEY])
            if  reset_pass_status == SendEmailStatus.SUCCESS:
                response_dict = {AppMsgs.MSG:AppMsgs.RESP_STATUS_SUCCESS, AppMsgs.IS_PASSWORD_RESET:True}
                response_dict = SimpleNamespace(**response_dict)
                return HttpResponse(json.dumps(ast.literal_eval(str(response_dict))), content_type=AppMsgs.CONTENT_TYPE_VALUE)
            else:
                response_dict = {AppMsgs.MSG:AppMsgs.RESP_STATUS_SUCCESS, AppMsgs.IS_PASSWORD_RESET:False}
                response_dict = SimpleNamespace(**response_dict)
                return HttpResponse(json.dumps(ast.literal_eval(str(response_dict))), content_type=AppMsgs.CONTENT_TYPE_VALUE)
        except Exception as e:
            response_dict = {AppMsgs.MSG:AppMsgs.RESP_STATUS_FAILURE, AppMsgs.IS_PASSWORD_RESET:False}
            response_dict = SimpleNamespace(**response_dict)
            return HttpResponse(json.dumps(ast.literal_eval(str(response_dict))), content_type=AppMsgs.CONTENT_TYPE_VALUE)

reset_password/templates/reset_password/call_approval.html
{% extends 'base.html'  %}

	{% block page_name %}Get Complete Access{% endblock %}

    {% block title %}Call Approval{% endblock title %}

    {% block head %}
    {% load static %}

               <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}" />
               <script type="text/javascript" src="{% static '/js/jquery.min.js' %} "></script>
               <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
               <script type="text/javascript" src="{% static '/js/acp_common.js' %} "></script>
               <script type="text/javascript" src="{% static '/js/jquery.loadmask.min.js' %} "></script>
                <script type="text/javascript" src="{% static '/js/main.js' %} "></script>
	 			<script src="{% static 'js/icheck/icheck.js' %}"></script>
				<link rel="stylesheet" type="text/css" href="{% static 'css/polaris.css' %}" />
				<script type="text/javascript" src="{% static 'reset_password/call_approval.js' %} "></script>

    {% endblock head %}



{% block content %}
<div class="row grid">
	<div class="col-sm-12">
		<div class="abcp-thankyou-msg-container">
			<form action="" method="post">{% csrf_token %}
			<div class="well well-lg abcp-thankyou-msg" style="background-color: #fff;">
				<h3 class="text-center" style="font-size: 23px;">To grant complete access to the portal, our Customer Service Representative needs to contact you at the following home phone {{phonehome}} between 09:00 a.m and 04:00 p.m hour(s). If the hours are acceptable, please acknowledge by hitting the 'Approved' button below. </h3>
				<div class="text-center"><input type="submit" value="Approve" class="btn btn-success btn-lg"></div>
			</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

reset_password/templates/reset_password/choose_reset_method.html
<html lang="en">

<head>
	<title>Reset Password</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/icheck/icheck.js' %}"></script>
	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'reset_password/reset_method.js' %}"></script>

</head>
<body class="abcp-contact-bg abcp-thanks-page">
	<div class="site-holder">
	{% include "header_before_login.html" %}
			<div class="abcp-footer-fix abcp-contact-content">
			<!-- .content -->
			<div class="abcp-content-holder no-margin-left">
<div class="row grid">
	<div class="col-md-12" id="div_3">
		    <div class="panel panel-primary abcp-category">
		        <div class="panel-heading">
		            <h2 class="panel-title acp-panel-title-color">
		            Recover your password
		        </h2>
		    </div>
		    <div class="panel-body">
		    
		        <div class="form-horizontal">
		        								<div id="dynamic_form">
								<form id="reset_pass_form" action="" method="post">
	
	<div class="form-group">
                    	<div class="col-lg-3 control-label"></div>
                    	<div class="col-lg-8">
                    	<div>
                    	<label>
                    	Please choose the contact method we should use for verification:
                    	</label>
                    	</div>
                    	<div class=""><input id="via_email" type="radio" name="reset_method_dd" value="1">&nbsp;&nbsp;<label for="via_email">via Email</label></div>
	                    <div class=""><input id="via_sms" type="radio" name="reset_method_dd" value="2">&nbsp;&nbsp;<label for="via_sms">via SMS</label></div>    
						</div>							
                    </div>

    <div class="row grid">
		<div id="div_3">
			<div class="panel panel-primary">
                    <div class="form-horizontal">
                        	<label class="col-lg-3 control-label"></label>
                            <div class="acp-reply-section col-lg-8">
                            	<div class="cbp_tmlabel acp-create-form">
                                	<span id="id_submit_container" title="">
                                    	<button id="rmethod_submit_btn" type="button" class="btn btn-reply btn-lg abcp-submit-btn">Submit</button>
                                    </span>
                                    <button type="button" class="btn btn-cancel btn-lg" onclick="return_to_login()">Cancel</button>
                                </div>
                            </div>
                    </div>
           </div>
        </div>
    </div>
</form>




</div>
							
                    
                     
                    
		        </div>
		    </div>
		    <!-- /panel body -->
		</div>
	</div>
</div>


					</div>

			</div>
			
			<!-- /.content -->

		{% include "footer_before_login.html" %}
		</div>
	
	
	

</body>


</html>

reset_password/templates/reset_password/get_customer_contact_info.html
{% extends 'base.html'  %}
	{% block page_name %} Customer Contact Info {% endblock %}
    {% block title %}Customer Contact Info{% endblock title %}

{% block head %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/summernote-bs3.css' %}" />
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/jquery.loadmask.min.js' %} "></script>
	<script type="text/javascript">
		var ua = navigator.userAgent.toLowerCase(); 
		if (ua.indexOf('safari') != -1) { 
		  if (ua.indexOf('chrome') > -1) {
			  // Chrome
		  } else {
			  document.write('<script src="//cdnjs.cloudflare.com/ajax/libs/webshim/1.16.0/dev/polyfiller.js"><\/script>');
		  }
		}
	</script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/bootstrapValidator.js' %}"></script>
	<script src="{% static 'js/summernote.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'tickets/main.js' %}"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>
	<script src="//igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>
	<script src="{% static 'js/icheck/icheck.js' %}"></script>
	<script src="{% static 'js/daterangepicker.js' %}"></script>
	<script src="{% static 'js/moment.js' %}"></script>
	<script src="{% static 'reset_password/customer_contact_info.js' %}" ></script>
{% endblock head %}

{% block content %}
<div class="row grid">
	<div class="col-md-12" id="div_3">
		    <div class="panel panel-primary abcp-category">
		        <div class="panel-heading">
		            <h2 class="panel-title acp-panel-title-color">
		             Customer Contact Info
		        </h2>
		    </div>
		    <div class="panel-body">
		        <div class="form-horizontal">
		        
                    

		
								<div id="customer_info_form_div">
								
								<form id="customer_info_form" action="" method="post">{% csrf_token %}
	
		<div class="form-group">
			<label class="col-lg-3 control-label"><label for="id_mbr">MBR:</label></label>
			<div class="col-lg-8"><input class="form-control" id="id_mbr" maxlength="100" name="mbr" value="{{mbr}}" type="text" required="" readonly></div>
		</div>
		
		<div class="form-group">		
			<label class="col-lg-3 control-label"><label for="id_name">Name:</label></label>
			<div class="col-lg-8"><input class="form-control" id="id_name" maxlength="100" name="name" value="{{customer_name}}" type="text" required="" readonly></div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-3 control-label"><label for="id_phone">Phone:</label></label>
			<div class="col-lg-8"><input class="form-control" id="id_phone" maxlength="10" name="phone" type="text" required=""></div>
			<small class="help-block col-lg-offset-3 col-lg-9 no-display atleast-one-req">Email/Phone is required</small>
		</div>
		
		<div class="form-group">
			<label class="col-lg-3 control-label"><label for="id_email">Email:</label></label>
			<div class="col-lg-8"><input class="form-control" id="id_email" maxlength="100" name="email" type="text" required=""></div>
			<small class="help-block col-lg-offset-3 col-lg-9 no-display atleast-one-req">Email/Phone is required</small>
		</div>
		
	

    <div class="row grid">
		<div id="div_3">
			<div class="panel panel-primary">
                    <div class="form-horizontal">
                        	<label class="col-lg-3 control-label"></label>
                            <div class="acp-reply-section col-lg-8">
                            	<div class="cbp_tmlabel acp-create-form">
                            	<!-- nput type="submit" value="Submit" class="btn btn-reply btn-lg abcp-submit-btn"-->
                            	<span id="id_submit_container" title="">
                                    	<button type="button" class="btn btn-reply btn-lg abcp-submit-btn" onclick="submit_form()">Submit</button>
                                    </span>
                                <button type="button" class="btn btn-cancel btn-lg" onclick="go_to_dashboard()">Cancel</button>
                                </div>
                            </div>
                    </div>
           </div>
        </div>
    </div>
</form>


</div>
							
                    
                     
                    
		        </div>
		    </div>
		    <!-- /panel body -->
		</div>
	</div>
</div>

{% endblock %}

reset_password/templates/reset_password/thanks_submit_contact_info.html
{% extends 'base.html'  %}

	{% block page_name %}Get Complete Access{% endblock %}

    {% block title %}Call Approval{% endblock title %}

    {% block head %}
    {% load static %}

               <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}" />
               <script type="text/javascript" src="{% static '/js/jquery.min.js' %} "></script>
               <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
               <script type="text/javascript" src="{% static '/js/acp_common.js' %} "></script>
               <script type="text/javascript" src="{% static '/js/jquery.loadmask.min.js' %} "></script>
                <script type="text/javascript" src="{% static '/js/main.js' %} "></script>
	 			<script src="{% static 'js/icheck/icheck.js' %}"></script>
				<link rel="stylesheet" type="text/css" href="{% static 'css/polaris.css' %}" />
    {% endblock head %}



{% block content %}
<div class="row grid">
	<div class="col-sm-12">
		<div class="abcp-thankyou-msg-container">
			<form action="" method="post">{% csrf_token %}
			<div class="well well-lg abcp-thankyou-msg" style="background-color: #fff;">
				<h3 class="text-center" style="font-size: 23px;">Thanks for submitting contact info. 
				CSR will contact you soon.</h3>
			</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}